### ISSUE TITLE
Code Review for HPE-LP-MentorMe-Services security/TokenHandler.java HPE Code Review

### ISSUE THREAD

**Issue by speguanco** [topcoderinc/HPE-LP-MentorMe-Services#1]
Service Implementation 1 Result:

![image](https://cloud.githubusercontent.com/assets/23239124/20094509/7d289bd6-a5dc-11e6-81a4-4919d398fe72.png)

**Comment by kinfkong** [comment]
I don't get it why we cannot use the "val", and I don't know how to fix.
Thanks

**Comment by ward-appirio** [comment]
This is false positive.  The code actually has introduced a new local variable rather than reusing the parameter value.
