### ISSUE TITLE
Code Review for HPE-LP-MentorMe-Services remote/consumers/JobResultConsumer.java HPE Code Review

### ISSUE THREAD

**Issue by speguanco** [topcoderinc/HPE-LP-MentorMe-Services#13]
Remote Service Implementation Challenge Result:

![image](https://cloud.githubusercontent.com/assets/23239124/20517088/8bac990c-b0d4-11e6-916e-8e47ffc8bf00.png)

**Comment by kinfkong** [comment]
I don't know why we cannot wrap to throw the run-time exception. Here:
1. we cannot rethrow InterruptedException, because the method did not declare this exception.
2. It is a really trivial problem, because it catch a sleep only. 
```
try {
                Thread.sleep(getWaitTime());
            } catch (InterruptedException e) {
                throw new IllegalStateException(e.getMessage(), e);
            }
```
