### ISSUE TITLE
Code Review for HPE-LP-MentorMe-Services exceptions/ServiceExceptionHandler.java HPE Code Review

### ISSUE THREAD

**Issue by speguanco** [topcoderinc/HPE-LP-MentorMe-Services#14]
Remote Service Implementation Challenge Result:

![image](https://cloud.githubusercontent.com/assets/23239124/20517156/d0663210-b0d4-11e6-99b3-08c1a83a9243.png)

**Comment by kinfkong** [comment]
Fixed
