### ISSUE TITLE
SecutiryConfigTest

### ISSUE THREAD

**Issue by cwdcwd** [topcoderinc/HPE-LP-MentorMe-Services#19]
### Description:
"Security" is misspelled as Secutiry in [this file](https://github.com/topcoderinc/HPE-LP-MentorMe-Services/blob/develop/src/test/java/com/livingprogress/mentorme/security/SecutiryConfigTest.java) name.

### Requirements:
- renamed file and any references 
 
### Submissions:
- Ensure good test coverage on all modules
- Upload documentation for how to run your submission
- Upload all your source code as a zip for review
- Winner will be required to submit a pull request with their winning code.

**Comment by kinfkong** [comment]
fixed
