### ISSUE TITLE
Code Review for HPE-LP-MentorMe-Services services/springdata/BaseService.java HPE Code Review

### ISSUE THREAD

**Issue by speguanco** [topcoderinc/HPE-LP-MentorMe-Services#2]
Service Implementation 1 Result:

![image](https://cloud.githubusercontent.com/assets/23239124/20094586/e6ad2df6-a5dc-11e6-9662-e963d388e51c.png)

**Comment by standlove** [comment]
There is not related code in the latest codebase ... 
The code-review comment seems a bit outdated.

**Comment by kinfkong** [comment]
Not an issue as standlove says.
