### ISSUE TITLE
Code Review for HPE-LP-MentorMe-Services utils/Helper.java HPE Code Review

### ISSUE THREAD

**Issue by speguanco** [topcoderinc/HPE-LP-MentorMe-Services#3]
Service Implementation 1 Result:

![image](https://cloud.githubusercontent.com/assets/23239124/20094693/5b7ae5d8-a5dd-11e6-831d-aed922a0b567.png)

![image](https://cloud.githubusercontent.com/assets/23239124/20094740/8eea3dba-a5dd-11e6-97d4-1c4c53288e04.png)

**Comment by kinfkong** [comment]
I don't get it why we cannot use the parameter "pd", and I do not know how to fix it.
Thanks

**Comment by kinfkong** [comment]
why cannot reuse the "pd"?
it pass in is to change it.
check the code:
```
    public static <T extends IdentifiableEntity> Predicate
    buildInPredicate(List<T> val, Predicate pd, Path<?> path, CriteriaBuilder cb) {
        if (val != null && !val.isEmpty()) {
            List<Long> ids = val.stream().map(IdentifiableEntity::getId).collect(Collectors.toList());
            return cb.and(pd, path.in(ids));
        }
        
        return pd;
    }
```

please clarify.
