### ISSUE TITLE
HPE-LP-MentorMe-Services controllers/ImageController.java

### ISSUE THREAD

**Issue by speguanco** [topcoderinc/HPE-LP-MentorMe-Services#34]
![image](https://cloud.githubusercontent.com/assets/23239124/21853714/2cc462c0-d853-11e6-9a15-2e6703857db5.png)

**Comment by kinfkong** [comment]
Fixed. refer to:
https://github.com/topcoderinc/HPE-LP-MentorMe/issues/194
