### ISSUE TITLE
HPE-LP-MentorMe-Services services/springdata/TaskServiceImpl.java

### ISSUE THREAD

**Issue by speguanco** [topcoderinc/HPE-LP-MentorMe-Services#35]
![image](https://cloud.githubusercontent.com/assets/23239124/21853784/620f8662-d853-11e6-9dbf-e3cedc2dad84.png)

**Comment by kinfkong** [comment]
Fixed. Refer to
https://github.com/topcoderinc/HPE-LP-MentorMe/issues/194
