### ISSUE TITLE
Code Review for HPE-LP-MentorMe-Services exceptions/ServiceExceptionHandler.java HPE Code Review

### ISSUE THREAD

**Issue by speguanco** [topcoderinc/HPE-LP-MentorMe-Services#4]
Service Implementation 1 Result:
![image](https://cloud.githubusercontent.com/assets/23239124/20094812/de23fccc-a5dd-11e6-8bc5-12e70fb38cb5.png)

**Comment by kinfkong** [comment]
duplicated to issue: #14
