### ISSUE TITLE
HPE-LP-MentorMe-Services security/CustomAuthenticationEntryPoint.java

### ISSUE THREAD

**Issue by speguanco** [topcoderinc/HPE-LP-MentorMe-Services#47]
![image](https://cloud.githubusercontent.com/assets/23239124/22193440/437bb1d6-e176-11e6-9904-27b989102b9e.png)

**Comment by kinfkong** [comment]
Fixed. refer to:
https://github.com/topcoderinc/HPE-LP-MentorMe/issues/194
